Repository pharapeti/e-library, pull requests merged in 2020-09, with the labels that each got.

#4 Integrate Travis CI for continuous integration
  .travis.yml
  config/database.yml.travis
  spec/rails_helper.rb
Labels: review please

#6 User type cleanup
  README.md
  app/controllers/books_controller.rb
  app/views/books/show.haml
  app/views/students/dashboard/show.haml
Labels: ready to merge

#8 US7: View Book content and borrow book
  app/assets/images/200x200_sample.png
  app/assets/images/sample_pdf.pdf
  app/assets/stylesheets/scaffolds.scss
  app/controllers/books_controller.rb
  app/models/book.rb
  app/models/loan.rb
  app/views/books/_form.haml
  app/views/books/index.haml
  app/views/books/show.haml
  app/views/students/dashboard/show.haml
  config/environments/development.rb
  config/routes.rb
  spec/features/staff/staff_borrows_book_spec.rb
  spec/features/students/student_borrows_book_spec.rb
  spec/fixtures/active_storage/200x200_sample.png
  spec/fixtures/active_storage/attachments.yml
  spec/fixtures/active_storage/blobs.yml
  spec/fixtures/active_storage/sample_pdf.pdf
  spec/fixtures/books.yml
  spec/fixtures/loans.yml
  spec/rails_helper.rb
Labels: review please

#7 Allows user to view and update their details
  .gitignore
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/layouts/staff.haml
  app/views/layouts/student.haml
  app/views/users/registrations/edit.haml
  spec/features/staff/account_registration_spec.rb
  spec/features/students/account_registration_spec.rb
  spec/features/users/user_changes_info_spec.rb
Labels: feedback requested

#9 Added First Name and Last Name to registration files and Conducted the tests for it
  app/controllers/users/registrations_controller.rb
  app/models/user.rb
  app/views/users/registrations/new.haml
  spec/features/staff/account_registration_spec.rb
  spec/features/students/account_registration_spec.rb
  spec/features/users/user_changes_info_spec.rb
Labels: feedback requested, review please

#11 Navigate Using Root Path when Access Denied
  app/controllers/application_controller.rb
Labels: ready to merge

#10 US006: Add Book
  app/controllers/books_controller.rb
  app/models/book.rb
  app/views/books/_form.haml
  app/views/books/new.haml
  db/migrate/20200928025756_drop_author_table.rb
  db/migrate/20200928025952_add_book_description_and_borrow_limit.rb
  db/migrate/20200928034513_change_book_edition_to_integer.rb
  db/migrate/20200928053352_change_book_amount_column_name.rb
  db/schema.rb
Labels: ready to merge

#13 Add dashboard route for library manager.
  app/controllers/library_managers/dashboard_controller.rb
  app/controllers/library_managers/library_managers_controller.rb
  app/controllers/static_controller.rb
  app/views/layouts/library_manager.haml
  app/views/library_managers/dashboard/show.haml
  config/routes.rb
Labels: ready to merge
